{% set version = "5.0.3" %}

package:
  name: graphblas
  version: {{ version }}

source:
  url: https://github.com/DrTimothyAldenDavis/GraphBLAS/archive/v{{ version }}.tar.gz
  sha256: d3113b5f87e04d9d61186113adf1b81632223597453c89d03b713a4d545253aa

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("graphblas", max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - m4  # [not win]
  host:
    - openmp  # [linux]
    - llvm-openmp  # [osx]
  run:
    - openmp  # [linux]
    - llvm-openmp  # [osx]

test:
  commands:
    - test -f ${PREFIX}/include/GraphBLAS.h  # [not win]
    - test -f ${PREFIX}/lib/libgraphblas${SHLIB_EXT}  # [not win]
    - test ! -e ${PREFIX}/lib/libgraphblas.a  # [not win]

about:
  home: https://github.com/DrTimothyAldenDavis/GraphBLAS
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: SuiteSparse:GraphBLAS is a full implementation of the GraphBLAS standard

extra:
  recipe-maintainers:
    - grlee77
    - jakirkham
    - basnijholt
    - minrk
    - jayfurmanek
    - jim22k
    - eriknw
